#!/bin/bash

cd rts || exit
make
cd .. || exit
cargo install --path . --root ~/.local --force --locked
base="$(basename -s .sw "$1")"
rm "$base" "$base".ll
swindle "$1" &> "$base".ll
clang -g "$base".ll -o "$base"
